services:
  valkey:
    image: valkey/valkey:8.0-alpine
    container_name: convertIA-valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

volumes:
  valkey_data: