services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - ./back/.env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://10.130.30.18:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "ollama.internal:10.130.30.18"
    networks:
      - convertia-net

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend:8000
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8083:8080"
    depends_on:
      - backend
    env_file:
      - ./front/.env
    networks:
      - convertia-net

networks:
  convertia-net:
    external: true